# 线性代数

In [1]:
import torch 

x=torch.tensor(1.0)
y=torch.tensor(2.0)

x+y,x*y,x/y,x**y

(tensor(3.), tensor(2.), tensor(0.5000), tensor(1.))

## 向量

In [3]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
x[3]

tensor(3)

In [5]:
len(x)

4

In [6]:
x.shape

torch.Size([4])

In [8]:
x=x.reshape((2,2))
x

tensor([[0, 1],
        [2, 3]])

In [9]:
x.shape

torch.Size([2, 2])

In [10]:
len(x)

2

## 矩阵

In [12]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [13]:
A[0][0]

tensor(0)

In [14]:
A[1][2]

tensor(6)

In [15]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [16]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [19]:
B==B.T #看是否是转置矩阵

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 张量

In [20]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [21]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [22]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [23]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [24]:
X.sum()

tensor(276)

In [25]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [26]:
A_sum_axis0=A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [27]:
A.sum(axis=[0,1])

tensor(190.)

In [28]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [29]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [30]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [31]:
A.mean(axis=1),A.sum(axis=1)/A.shape[1]

(tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]),
 tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]))

In [32]:
sum_A=A.sum(axis=1,keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [33]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [34]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## 点积

In [45]:
y=torch.ones(4,dtype=torch.float32)
x=x.reshape(-1)
x=x.float()
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [46]:
torch.sum(x*y)

tensor(6.)

## 矩阵，向量积

In [47]:
A,x

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]))

In [48]:
A.shape,x.shape

(torch.Size([5, 4]), torch.Size([4]))

In [49]:
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])

In [50]:
B=torch.ones(4,3)
A,B,torch.mm(A,B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

## 范数

In [51]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [52]:
torch.abs(u).sum()

tensor(7.)

In [53]:
torch.norm(torch.ones((4,9)))

tensor(6.)

范数（Norm）是一个函数，它将一个向量映射到一个非负实数，表示向量的“大小”或“长度”。在机器学习、数值分析和向量空间中，范数是非常重要的概念。不同的范数定义方式可以强调向量的不同特性。下面介绍一些常见的范数及其应用。

### 常见的范数

1. **L1范数（曼哈顿范数或绝对值范数）**
   - 定义：一个向量的所有元素的绝对值之和。
   - 数学表达：对于向量 \( \mathbf{x} = [x_1, x_2, \ldots, x_n] \)，L1范数为 \( \|\mathbf{x}\|_1 = \sum_{i=1}^n |x_i| \)。
   - 应用：在稀疏编码和LASSO回归中使用较多，倾向于产生稀疏解。

2. **L2范数（欧几里得范数）**
   - 定义：一个向量的所有元素的平方和的平方根。
   - 数学表达：对于向量 \( \mathbf{x} = [x_1, x_2, \ldots, x_n] \)，L2范数为 \( \|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2} \)。
   - 应用：在许多机器学习算法中广泛使用，如线性回归、神经网络等。它衡量向量的长度或距离。

3. **无穷范数（最大范数）**
   - 定义：向量中具有最大绝对值的元素。
   - 数学表达：对于向量 \( \mathbf{x} = [x_1, x_2, \ldots, x_n] \)，无穷范数为 \( \|\mathbf{x}\|_\infty = \max_i |x_i| \)。
   - 应用：在优化和稳定性分析中使用，尤其在确定最大的单个误差或变化时。

### PyTorch中的范数计算

在 PyTorch 中，你可以使用 `torch.norm` 函数来计算不同类型的范数。下面是一些例子：

```python
import torch

# 创建一个示例张量
x = torch.tensor([1.0, -2.0, 3.0, -4.0])

# 计算 L1 范数
l1_norm = torch.norm(x, p=1)
print("L1 范数:", l1_norm)

# 计算 L2 范数
l2_norm = torch.norm(x, p=2)
print("L2 范数:", l2_norm)

# 计算无穷范数
inf_norm = torch.norm(x, p=float('inf'))
print("无穷范数:", inf_norm)
```

输出结果：

```
L1 范数: 10.0
L2 范数: 5.477225575051661
无穷范数: 4.0
```

### 范数的应用

1. **数据预处理**：在机器学习中，常常需要对数据进行标准化或归一化处理，以便不同特征具有相同的尺度。L2 范数通常用于标准化。
2. **损失函数**：在优化问题中，L1 和 L2 范数常用于构造正则化项，以防止模型过拟合。
3. **距离度量**：在聚类和最近邻算法中，L2 范数用于计算欧几里得距离，而 L1 范数用于计算曼哈顿距离。

### 总结

范数是衡量向量长度或大小的重要工具，根据具体问题的需求可以选择不同的范数类型。在 PyTorch 中，使用 `torch.norm` 函数可以方便地计算不同类型的范数。理解和应用范数对于数据处理、模型训练和优化问题的解决都有重要意义。

如果你有任何其他问题或需要进一步的解释，请随时告诉我！

In [54]:
len(X)

2

In [55]:
len(X[0])

3

In [56]:
len(X[0][0])

4

In [57]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [59]:
A/A.sum(axis=1,keepdims=True)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [60]:
Z=torch.arange(24).reshape((2,3,4))
Z

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [63]:
sum_0=Z.sum(axis=0)
print(sum_0.shape)

torch.Size([3, 4])


In [64]:
sum_0

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

In [65]:
sum_1=Z.sum(axis=1)
sum_1

tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

In [66]:
sum_2=Z.sum(axis=2)
sum_2

tensor([[ 6, 22, 38],
        [54, 70, 86]])

In [67]:
sum_0.shape,sum_1.shape,sum_2.shape

(torch.Size([3, 4]), torch.Size([2, 4]), torch.Size([2, 3]))